name: chit_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: ^4.2.1
  firebase_core: ^0.3.0
  firebase_auth: ^0.8.4+4
  cloud_firestore: ^0.9.13+1
  modal_progress_hud: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_app_name: ^0.1.1

flutter_app_name:
  name: "Chit Chat"

flutter:
  fonts:
    - family: AmaticSC
      fonts:
        - asset: fonts/AmaticSC-Bold.ttf
    - family: ArchitectsDaughter
      fonts:
        - asset: fonts/ArchitectsDaughter-Regular.ttf
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-VariableFont_wght.ttf

  uses-material-design: true

  assets:
    - images/
